-- MySQL Script generated by MySQL Workbench
-- 08/16/17 11:52:53
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema creaciones
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `creaciones` ;

-- -----------------------------------------------------
-- Schema creaciones
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `creaciones` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
SHOW WARNINGS;
USE `creaciones` ;

-- -----------------------------------------------------
-- Table `PERSONA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PERSONA` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `PERSONA` (
  `idpersona` INT NOT NULL COMMENT '',
  `cedula` INT NULL COMMENT '',
  `nombres` VARCHAR(140) NULL COMMENT '',
  `telefono` INT NULL COMMENT '',
  PRIMARY KEY (`idpersona`)  COMMENT '')
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `CLIENTE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CLIENTE` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `CLIENTE` (
  `idcliente` INT NOT NULL COMMENT '',
  `estado` INT NULL COMMENT '',
  `idpersona` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idcliente`)  COMMENT '')
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `TIPO_PRODUCTO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TIPO_PRODUCTO` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `TIPO_PRODUCTO` (
  `idtipoprod` INT NOT NULL COMMENT '',
  `nomtipoprod` VARCHAR(200) NULL COMMENT '',
  `estado` INT NULL COMMENT '',
  PRIMARY KEY (`idtipoprod`)  COMMENT '')
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `PEDIDO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PEDIDO` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `PEDIDO` (
  `idpedido` INT NOT NULL COMMENT '',
  `factura` VARCHAR(45) NOT NULL COMMENT '',
  `cantidad` INT NULL COMMENT '',
  `talla` VARCHAR(4) NULL COMMENT '',
  `descripcion` VARCHAR(200) NULL COMMENT '',
  `fecha_ingreso` DATE NULL COMMENT '',
  `idcliente` INT NOT NULL COMMENT '',
  `idtipoprod` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idpedido`)  COMMENT '')
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `PRODUCTO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PRODUCTO` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `PRODUCTO` (
  `id_prod` INT NOT NULL COMMENT '',
  `nomprod` VARCHAR(200) NULL COMMENT '',
  `estado` INT NULL COMMENT '',
  `idtipoprod` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id_prod`)  COMMENT '')
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `PRECIO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PRECIO` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `PRECIO` (
  `idprecio` INT NOT NULL COMMENT '',
  `estado` VARCHAR(45) NULL COMMENT '',
  `fecha` DATE NULL COMMENT '',
  `valor` INT NULL COMMENT '',
  `subvalor` INT NULL COMMENT '',
  `id_prod` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idprecio`)  COMMENT '')
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `USUARIOS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `USUARIOS` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `USUARIOS` (
  `idusuarios` INT NOT NULL COMMENT '',
  `name` VARCHAR(45) NULL COMMENT '',
  `password` VARCHAR(45) NULL COMMENT '',
  `tipo` INT NULL COMMENT '',
  `estado` INT NULL COMMENT '',
  `idpersona` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idusuarios`)  COMMENT '')
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `PROCESO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PROCESO` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `PROCESO` (
  `idproceso` INT NOT NULL COMMENT '',
  `cantidad` VARCHAR(45) NULL COMMENT '',
  `estado` VARCHAR(45) NULL COMMENT '',
  `fecha` DATE NULL COMMENT '',
  `id_prod` INT NOT NULL COMMENT '',
  `idpedido` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idproceso`)  COMMENT '')
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
